<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <ProjectReference Include="..\SmartParking.UserService.Application\SmartParking.UserService.Application.csproj" />
    <ProjectReference Include="..\SmartParking.UserService.Domain\SmartParking.UserService.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>8a1bc4b0-f3b6-4da0-afac-05c5c4c18b90</UserSecretsId>
  </PropertyGroup>

</Project>
