import { useEffect, useState } from 'react';
import { request } from '../../../lib/authApi';
import type { OwnerApplicationRecord } from '../../../lib/ownerApi';
export function OwnerVerification({ application, onVerified }: { application:Pick<OwnerApplicationRecord,'email'|'verification'|'phoneVerification'>;onVerified:()=>void }) {
  const [step,setStep]=useState(()=>{try{return localStorage.getItem('sp_owner_verification_step')==='1'?1:0;}catch{return 0;}});const [code,setCode]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const challenge=step===0?application.verification:application.phoneVerification;
  useEffect(()=>{let active=true;request<{data:{emailVerified:boolean;phoneVerified:boolean}}>('/register/owner/recover','POST',{contact:application.email}).then(r=>{if(!active)return;if(r.data.emailVerified && r.data.phoneVerified)onVerified();else setStep(r.data.emailVerified?1:0);}).catch(()=>{/* Existing challenges can still be retried. */});return()=>{active=false;};},[application.email]);
  async function verify(e:React.FormEvent){e.preventDefault();if(!challenge)return;setBusy(true);setMessage('');try{await request('/register/owner/verify','POST',{challengeId:challenge.challengeId,code});if(step===0){setStep(1);try{localStorage.setItem('sp_owner_verification_step','1');}catch{/* Current tab retains progress. */}setCode('');}else onVerified();}catch(e){setMessage(e instanceof Error?e.message:'Verification failed.');}finally{setBusy(false);}}
  async function resend(){if(!challenge)return;setBusy(true);try{await request('/register/owner/resend','POST',{registrationId:challenge.challengeId});setMessage('A new code is queued.');}catch(e){setMessage(e instanceof Error?e.message:'Retry failed.');}finally{setBusy(false);}}
  return <form className="card" onSubmit={verify}><h2>Verify {step===0?'email':'phone'}</h2><p>Verify both contacts before your application can be approved.</p><label className="label" htmlFor="owner-code">Verification code</label><input id="owner-code" className="input" required pattern="[0-9]{6}" maxLength={6} inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)} disabled={busy}/><p role="status">{message}</p><button className="btn-primary" disabled={busy}>Verify</button><button type="button" className="btn-outline" disabled={busy} onClick={()=>void resend()}>Resend code</button></form>;
}
