<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><UserSecretsId>SmartParking.ReservationService.API.LocalDevelopment</UserSecretsId></PropertyGroup>
  <ItemGroup><ProjectReference Include="../SmartParking.ReservationService.Persistence/SmartParking.ReservationService.Persistence.csproj" /></ItemGroup>
</Project>
