@SmartParking.User.API_HostAddress = http://localhost:5035

POST {{SmartParking.User.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "driver@gmail.com",
  "password": "Password@123"
}

###
