<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>  <UserSecretsId>d85068c2-9c08-4313-a95e-f207ccede001</UserSecretsId>
  </PropertyGroup>
  <ItemGroup><PackageReference Include="Npgsql" Version="10.0.3" /><ProjectReference Include="../SmartParking.ParkingService.Application/SmartParking.ParkingService.Application.csproj" /></ItemGroup>
</Project>
