<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>  <UserSecretsId>33399551-4f27-4a06-a4b7-675124b6ca27</UserSecretsId>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../SmartParking.ParkingService.Domain/SmartParking.ParkingService.Domain.csproj" /></ItemGroup>
</Project>
